workflows:
  build-android:
    name: Build Android APK (debug)
    environment:
      flutter: 3.22.1
    scripts:
      - flutter pub get
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    publishing:
      email:
        recipients:
          - isaiasdesouzamkt@gmail.com
