workflows:
  build_android:
    name: Build Android App # É bom ter um nome para o workflow
    max_build_duration: 30 # Esta linha deve estar no mesmo nível que 'name', 'environment', etc.
    environment:
      flutter: stable
      xcode: false
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get

      - name: Clean build
        script: |
          flutter clean

      - name: Build APK Release
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
