workflows:
  build_android:
      max_build_duration: 30
          environment:
                flutter: stable
                      xcode: false
                          scripts:
                                - name: Get dependencies
                                        script: |
                                                  flutter pub get

                                                        - name: Clean build
                                                                script: |
                                                                          flutter clean

                                                                                - name: Build APK Release
                                                                                        script: |
                                                                                                  flutter build apk --release

                                                                                                      artifacts:
                                                                                                            - build/app/outputs/flutter-apk/app-release.APK