name: ds_one
description: DS-ONE v1 – Assistente IA local
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.5 
  speech_to_text: ^6.6.1
  avatar_glow: ^2.0.2
  flutter_tts: ^3.8.4
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  speech_to_text: 6.6.1