name: ds_one
description: Assistente pessoal ultra inteligente – DS‑ONE / LYARA
publish_to: "none"
version: 1.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.1"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Áudio e voz
  speech_to_text: ^6.7.0
  flutter_tts: ^4.0.3

  # Câmera e Visão
  camera: ^0.11.0
  google_mlkit_text_recognition: ^0.12.0
  tflite_flutter: ^0.10.3

  # Integrações externas
  url_launcher: ^6.2.7
  http: ^0.13.6

  # Visual e animações
  lottie: ^2.7.0
  flutter_spinkit: ^5.2.0

  # Controle de estado
  provider: ^6.1.2

  # Armazenamento temporário
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/animations/lyara_talking.json
    - assets/images/invest_icon.png
    - assets/images/vision_icon.png
