workflows:
  build-android:
      name: Build Android APK
          environment:
                flutter: stable
                    scripts:
                          - name: Get Flutter dependencies
                                  script: flutter pub get
                                        - name: Build debug APK
                                                script: flutter build apk --debug
                                                    artifacts:
                                                          - build/app/outputs/flutter-apk/app-debug.apk